export const ADD_NEW_SCHOOL = "ADD_NEW_SCHOOL";
export const REMOVE_SCHOOL = "REMOVE_SCHOOL";
export const REGISTER_COURSE = "REGISTER_COURSE";
export const START_LEARNING_GROUP = "START_LEARNING_GROUP";
export const REMOVE_LEARNING_GROUP = "REMOVE_LEARNING_GROUP";
export const DONE_LESSON = "DONE_LESSON";
